### ISSUE TITLE
A question in sec 5.1.

### ISSUE THREAD

**Issue by Luciferbobo** [ucla-rlcourse/cs260r-assignment-2023fall#13]
Hi, all. thx for this great work. 

I have a small question in sec 5.1, and I'm not sure if its a bug. In update_baseline() function, it appears that values and baselines are not of the same data type. values has been converted to float32 using to_tensor() function, while baselines hasn't undergone this conversion and remains of dtype int64. Consequently, this leads to a "RuntimeError: Found dtype Long but expected Float" .

Additionally, the default gradient for values here seems to be disabled. This results in "RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn". I dont know whether the issue is related to the torch version provided by Colab differing from the version when writing the notebook.

For above problems, I found that manually setting values.requires_grad = True and adding .type(torch.float32) after self.baseline(obs) work for me.

<img width="570" alt="df78b61802d5a4c48105bf3023075f0" src="https://github.com/ucla-rlcourse/cs260r-assignment-2023fall/assets/54936491/7194b27e-d0ac-4927-84ea-7e2fb32a4ef0">

**Comment by pengzhenghao** [comment]
> while baselines hasn't undergone this conversion and remains of dtype int64.

why? Baseline should be floating number.

> the default gradient for values here seems to be disabled

why? who disables it?

> For above problems, I found that manually setting values.requires_grad = True and adding .type(torch.float32) after self.baseline(obs) work for me.

That's terrible I don't know why it works.
